### ISSUE TITLE
Support for Microsoft.Insights/metricAlerts

### ISSUE THREAD

**Issue by ErtelK** [tfitzmac/resource-capabilities#3]
The table indicates that Microsoft.Insights/metricAlerts resources support tags; we have a process which goes through all resources which accept tags and verifies tags are set.  When it reaches resources of this type and attempts to set the tags on them we receive the following:

Set-AzResource: <HTML><HEAD>
<TITLE>Unsupported Request</TITLE>
</HEAD><BODY>
<H1>Unsupported Request</H1>
PATCH to http&#58;&#47;&#47;go&#46;microsoft&#46;com&#47;fwlink&#47;&#63; not supported.<P>
Reference&#32;&#35;8&#46;3409e8ac&#46;1589484303&#46;a20b7d12
</BODY></HTML>

**Comment by tfitzmac** [comment]
Sorry for the delay in getting back to you about this issue. I have verified metricalerts supports tags.
